name = "fee-tracker"
type = "javascript"
account_id = ""  e52b5f1e36b7b0b8a90062693ca28ffa
workers_dev = true
routes = []
zone_id = ""     # Only needed if deploying to a custom domain

# Pages configuration
[build]
command = "npm run build"
cwd = "./"

[build.upload]
format = "service-worker"

[env.production]
account_id = ""  e52b5f1e36b7b0b8a90062693ca28ffa
